# Generated by Django 6.0.4 on 2026-04-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="city",
            field=models.CharField(default="chad", max_length=20),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="state",
            field=models.CharField(default="chad", max_length=2),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="zip_code",
            field=models.SmallIntegerField(default="chad", max_length=5),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="address",
            field=models.CharField(max_length=255),
        ),
    ]
