# Generated by Django 6.0.4 on 2026-04-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_restaurant_city_restaurant_state_restaurant_zip_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="zip_code",
            field=models.BigIntegerField(default=11111, max_length=5),
        ),
    ]
