# Generated by Django 6.0.4 on 2026-04-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_restaurant_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="zip_code",
            field=models.BigIntegerField(max_length=5),
        ),
    ]
