# Generated by Django 6.0.4 on 2026-04-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_restaurant_zip_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="zip_code",
            field=models.BigIntegerField(default=11111, max_length=5),
        ),
    ]
