# Generated by Django 6.0.4 on 2026-04-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_restaurant_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="zip_code",
            field=models.BigIntegerField(default=11111),
        ),
    ]
